# Generated by Django 3.0.2 on 2020-01-21 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resource',
            table='resource',
        ),
    ]
