# Generated by Django 3.0.2 on 2020-01-21 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0002_auto_20200121_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name_plural': 'resources'},
        ),
        migrations.AlterModelTable(
            name='meetingminutes',
            table='attendance',
        ),
    ]
