# Generated by Django 3.0.2 on 2020-01-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0003_auto_20200121_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
