# Generated by Django 3.0.2 on 2020-02-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0004_event_eventurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventtime',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='MeetingMinutes',
        ),
    ]
